import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import {useEffect} from 'react'
import { fetchProducts } from '../../lib/products'
import { useProducts } from '@/hooks/swrHooks'

import ProductCard from '@/components/productCard'

import styles from 'styles/base/store.module.css'

export default function Product({addToCart, products}) {

  const {allProducts, error, loading} = useProducts(products)

  return (
    <div>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.products_container}>
        <div className={styles.products_board}>
          <p>Store</p>
        </div>
        <div className={styles.products}>
        {allProducts?.map((product, idx)=>(
            <ProductCard key={idx} product={product}/>
        ))
        }
        </div>
      </main>
        
    </div>
  )
}

export async function getStaticProps(context){

  const products = await fetchProducts()

  return{
    props:{
      products
    }
  }


}