import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
// import styles from '../styles/product.module.css'

import { fetchProductPaths, fetchProducts, fetchProduct } from '../../lib/products'

export default function Product({increment, addToCart, product}) {
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <p>{product.name}</p>
          <p>${product.price}</p>
          <p>{product.desc}</p>
        </div>
      </main>
        
    </div>
  )
}

//Turn into a dynamic route
export async function getStaticPaths(){
  const paths = await fetchProductPaths();
  return {
      paths:paths,
      fallback:false
  }
}

export async function getStaticProps({params}){

  let product = await fetchProduct(params.product)

  return {
    props:{
      product:product
    }
  }
}