import ProductCard from '@/components/productCard'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import {useState, useEffect, useRef} from 'react'
import styles from 'styles/base/shop.module.css'
import nookies from 'nookies'
import Filter from '@/components/modals/filter'
import axiosInstance from '@/lib/api/baseAxios'

import { fetchShopPaths, fetchShop } from '../../lib/shops'

export default function Shop({shop_detail}) {

  const [listings, setListings] = useState([])
  const [filtered, setFiltered] = useState([])

  const [modal, setModal] = useState(false)
  const description = useRef(null)
  const container = useRef(null)

  const [show, setShow] = useState(false)
  const [collapse, setCollapse] = useState(false)

  const toggleModal = ()=>{
    setModal(prev=>!prev)
  }

  const applyFilter = (min, max, category, sortby) =>{

    let filtered = [...listings]

    //filter price
    if(min>0 || max>0){
        filtered = filtered.filter(item => item.price >= min)
        filtered = filtered.filter(item => item.price <= max)
        console.log("Price")
        console.log({filtered})
    }

    //filter category
    if(category != "" && category != "-- Category"){
        filtered = filtered.filter(item => item.category == category)
        console.log("Cat")
        console.log({filtered})
    }

    //sorting
    if(sortby != "none"){
        switch (sortby){
            case "lowest_price":
                filtered = filtered.sort((a,b)=> a.price - b.price)
                break
            case "highest_price":
                filtered = filtered.sort((a,b) => b.price - a.price)
                break
            case "rating":
                filtered = filtered.sort((a,b) => b.rating - a.rating)
                break
            case "recent":
                filtered = filtered.sort((a,b) => a.createdAt - b.createdAt)
                break
        }
        console.log("sort")
        console.log({filtered})
    }

    console.log({filtered})
    setFiltered(filtered)
    
  }

  useEffect(()=>{

    const fetchProducts = async () =>{
     
      await axiosInstance.get(`/shops/${shop_detail._id}/get-products`).then(res=> res.data).then(data=>{
        setListings(data.products)
        setFiltered(data.products)
      })

    }

    fetchProducts()
    console.log(description.current.clientHeight)
    console.log(container.current.clientHeight)
    if(description.current.clientHeight > container.current.clientHeight){
      setCollapse(true)
    }
    // description.current

  },[])

  
  return (
    <div>
      <Head>
        <title>{shop_detail.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.product_wrapper}>
        <div className={styles.shop}>
          <div  className={styles.image}>
            <div ref={container} className={styles.image_container}>
              <img className={styles.img_src} src={shop_detail.image}/>
            </div>
          </div>
          <div ref={description}className={styles.details}>
            <p className={styles.name}>{shop_detail.name}</p>
            <p className={styles.sales}>{shop_detail.sales.length} Sales</p>
            <p className={show ? [styles.description, styles.show].join(" ") : styles.description}>{shop_detail.description} adsasd asd asd asd as dasd asd as dasd asd asd as das dasd as da sda sd asd as da sd as da sd a sda sdasdasd asdasd asdasd asdasd asdasd asdasd asdasd asd iauhsd iuahsd iauhsd iausdhasiduh asiduha sdiuha sdiuahsd iuahsdi uashd iausdh iaushd iausdh iausdh iausdh aiushd iaushd iausdh iausdh iaushd oias douahs diau sdhiaudh iaushd iaushd iaushd iaushdiau sdhiaushd iaushd iaushd iaushd iaushd iausd hiaushd iaushd iausdh iaushdiau sdhiaus dhiaus dha isudhaisdu haisudhai usdha isudh aisu dhia usdhia usdhia sudh asd asd asd asd asd asdasdasd asdasd asdasd eeeasd asd a asd 
              {!show && collapse &&
                <span className={styles.more} onClick={()=>setShow(prev =>!prev)}>more...</span>
              }
            </p>
          </div>
        </div>
        <div className={styles.products}>
          <div className={styles.float_container}>
            <div className={styles.filtering} onClick={toggleModal}>
                <p>Filter and sort</p>
            </div>
          </div>
          <div className={styles.list}>
            {filtered.length > 0 ?
              filtered.map((product)=>(
                <ProductCard product={product}/>
              ))
              :
                <p>No listings</p>
            }
            <div className={styles.product}></div>
            <div className={styles.product}></div>
            <div className={styles.product}></div>
            <div className={styles.product}></div>
            <div className={styles.product}></div>
            <div className={styles.product}></div>
            <div className={styles.product}></div>
            <div className={styles.product}></div>

          </div>
        </div>
      </main>
      {modal &&
        <Filter toggle={toggleModal} apply={applyFilter}/>
      }  
      
    </div>
  )
}

//Turn into a dynamic route
export async function getStaticPaths(){

  const paths = await fetchShopPaths();
  return {
      paths:paths,
      fallback:false
  }

}

export async function getStaticProps({params}){

  let shop = await fetchShop(params.shop)

  console.log(shop)

  return {
    props:{
      shop_detail:shop
    }
  }
}