import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
// import styles from '../../styles/product.module.css'

import { fetchProductPaths, fetchProducts, fetchProduct } from '../../lib/products'
import {fetchShopPaths, fetchShop} from '../../lib/shops'

export default function Product({shop}) {


  
  return (
    <div>
      <Head>
        <title>{shop.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.product_wrapper}>
        <div className={styles.product_container}>

          <div className={styles.main_product}>
            <div className={styles.product_details}>
              <p className={styles.product_name}>{shop.name}</p>
              <div className={styles.product_description}>
                <p className={styles.desc}>{product.desc}</p>
              </div>
              <p className={styles.desc1}><span>Material:</span> {product.material}</p>
              <p className={styles.desc1}><span>Diameter:</span> {product.diameter} </p>
              <p className={styles.desc2}><span>Size:</span> {product.size}</p>
              <p className={styles.product_price}>{product.price} SAMO</p>
              <button className={blocking ? styles.blocking : styles.add} onClick={()=>{
                
                //adding to cart
                if(!blocking){
                  addToCart({
                    productId:product._id,
                    name:product.name,
                    price:product.price
                  })
                }
              
              }}>{blocking ? "Adding.." :"Add to cart"}</button>
            </div>
            <div className={styles.product_image}>
              <img src="/main_home.png"/>
            </div>
          </div>

        </div>
      </main>
        
    </div>
  )
}

//Turn into a dynamic route
export async function getStaticPaths(){
  const paths = await fetchProductPaths();
  return {
      paths:paths,
      fallback:false
  }
}

export async function getStaticProps({params}){

  let product = await fetch(params.product)

  return {
    props:{
      shop:product
    }
  }
}