import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import {useEffect} from 'react'
import { fetchProducts } from '../../lib/products'

import ProductCard from '../../components/productCard'

import styles from '../../styles/shop.module.css'

export default function Product({addToCart, products}) {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.products_container}>
        <div className={styles.products}>
        {products.map((product, idx)=>(
            <ProductCard key={idx} product={product}/>
        ))
        }
        </div>


      </main>
        
    </div>
  )
}

export async function getStaticProps(context){

  const products = await fetchProducts()

  return{
    props:{
      products
    }
  }


}