import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
// import styles from '../styles/product.module.css'

export default function Product({increment, addToCart}) {
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p>This is the product</p>
      </main>
        
    </div>
  )
}

//Turn into a dynamic route