import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from 'styles/profile/orders.module.css'
import AuthenticatedRoute from '@/components/authenticatedRoute'
import Order from '@/components/Order'

import {useState, useEffect} from 'react'

export default function Orders({user}) {

  const [show, setShow] = useState(false)
  const [current, setCurrent] = useState({})


  const [orders, setOrders] = useState([])

  const showElement = (item)=>{
    setShow(true)
    setCurrent(item)
  }

  const hideElement = () => {
    setShow(false)
    setCurrent({})
  }

  useEffect(()=>{

    const fetchStats = async ()=>{
      await fetch(`http://localhost:8000/user/${user}/get-orders`, {
        method:'GET',
        headers:{
          'Content-Type':'application/json',
          'Access-Control-Allow-Origin':'cors'
        },
        mode:'cors'
      }).then(async res=>await res.json()).then(data =>{
        setOrders(data)
      })
    }

    fetchStats()

  },[])


  return (
    <AuthenticatedRoute>
      <div>
        <Head>
          <title>Profile</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={!show ? styles.container : [styles.container, styles.show].join(" ")}>
          <div className={styles.list}>         
            <p>Orders</p>
            <span>All completed orders</span>
            {orders.map((item)=>(
              <div onClick={()=>{
                showElement(item)
              }} className={styles.order}>
                {item._id}
                {item.subtotal}
              </div>
            ))

            }
          </div> 
          <div className={styles.details}>
            {Object.keys(current).length > 0 &&
              <Order toggle={hideElement} order={current}/>
            }
          </div>
        </main>
      </div>
    </AuthenticatedRoute>
  )
}