import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from 'styles/profile/reviews.module.css'
import AuthenticatedRoute from '@/components/authenticatedRoute'
import Review from '@/components/Review'

import {useState, useEffect} from 'react'

export default function Orders() {

  const [show, setShow] = useState(false)
  const [current, setCurrent] = useState({})

  const toggleElement = ()=>{
    setShow(prev => !prev)
  }

  return (
    <AuthenticatedRoute>
      <div>
        <Head>
          <title>Profile</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={!show ? styles.container : [styles.container, styles.show].join(" ")}>
          <div className={styles.list}>         
            <p>Reviews</p>
            <span>All pending reviews</span>
            <div onClick={()=>{
              toggleElement()
            }} className={styles.product}>
            </div>
            <div onClick={()=>{
              toggleElement()
            }} className={styles.product}>
            </div>
          </div> 
          <div className={styles.details}>
            <Review toggle={toggleElement} order={current}/>
          </div>
        </main>
      </div>
    </AuthenticatedRoute>
  )
}