import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/checkout.module.css'
import ConnectToPhantom from '../components/connectPhantom'

export default function Checkout({order}) {
  return (
    <div>
        <Head>
            <title>Checkout</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.checkout_wrapper}>
            <div className={styles.checkout_main}>
                <p className={styles.checkout_title}>CHECKOUT</p>
                <div className={styles.checkout_container}>
                    <div className={styles.checkout_details}>
                        <div className={styles.section}>
                            <div className={styles.title}>
                                <p>Customer</p>
                                <div className={styles.nums}>
                                    <p>1</p>
                                </div>
                            </div>
                            <p>Sign in or continue as guest</p>
                            <form className={styles.continue}>
                                <input type="email" id='email' placeholder='Email address'/>
                                <button>Continue</button>
                            </form>
                        </div>
                        <div className={styles.section}>
                            <div className={styles.title}>
                                <p>Delivery</p>
                                <div className={styles.nums}>
                                    <p>2</p>
                                </div>
                            </div>
                            <form className={styles.form_container}>
                                <div className={styles.location}>
                                    <input placeholder='Country'/>
                                    <input placeholder='City'/>
                                </div>
                                <input placeholder='P.O. Box'/>
                                <input placeholder='Phone Number'/>
                            </form>
                        </div>
                        <div className={styles.section}>
                            <div className={styles.title}>
                                <p>Billing</p>
                                <div className={styles.nums}>
                                    <p>3</p>
                                </div>
                            </div>
                            <div className={styles.billing}>
                                <ConnectToPhantom/>
                            </div>
                        </div>

                    </div>
                    <div className={styles.checkout_summary}>
                        <div className={styles.order}>
                            <p className={styles.order_title}>Your order</p>
                            {order && order.items.length != 0 ? <>
                            {order.items.map((item, idx)=>(
                                <div className={styles.item} key={idx}>
                                    <div className={styles.quantity}>
                                        <p>{item.quantity}</p>
                                        <p>x</p>
                                        <p> {item.name}</p>
                                    </div>
                                    <p>${item.price}</p>
                                </div>
                            ))}
                            <div className={styles.subtotal}>
                                <p>Subtotal</p>
                                <p className={styles.total}>${order.subtotal}</p>
                            </div>
                            </>
                            :
                            <div className={styles.empty_state}>
                            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M15.55 13c.75 0 1.41-.41 1.75-1.03l3.58-6.49c.37-.66-.11-1.48-.87-1.48H5.21l-.94-2H1v2h2l3.6 7.59-1.35 2.44C4.52 15.37 5.48 17 7 17h12v-2H7l1.1-2h7.45zM6.16 6h12.15l-2.76 5H8.53L6.16 6zM7 18c-1.1 0-1.99.9-1.99 2S5.9 22 7 22s2-.9 2-2-.9-2-2-2zm10 0c-1.1 0-1.99.9-1.99 2s.89 2 1.99 2 2-.9 2-2-.9-2-2-2z"/></svg>
                            <p>Your shopping cart is empty!</p> 
                            </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
  )
}
