import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

import AuthenticatedRoute from '../components/authenticatedRoute'

export default function Profile() {
  return (
    <AuthenticatedRoute>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          profile
        </main>
          
      </div>
      </AuthenticatedRoute>
  )
}